### ISSUE TITLE
Use readline-like key bindings (ctrl-a, ctrl-e, left, right that behave like in bash)

### ISSUE THREAD

**Issue by 0x0f0f0f** [chrisnevers/ocamline#3]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
ctrl-a, ctrl-e, left, right that behave like readline programs (like bash)

**Comment by 0x0f0f0f** [comment]
P.s. I adopted this in minicaml :)

**Comment by chrisnevers** [comment]
Thanks for the suggestion! This solution has been merged into `master`, I've integrated `ocaml-linenoise` to provide command history, left-right arrow, ctr+a ctr+e control. Will create a release within the next week or so
